import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:productive_flutter/v2/features/home/feeds/feed/models/feed_item.dart';

final feedProvider = FutureProvider<List<FeedItem>>((ref) async {
  final List<dynamic> feedItemsJson = feedData['feedItems'];
  return feedItemsJson.map((json) => FeedItem.fromJson(json)).toList();
});
final Map<String, dynamic> feedData = {
  "feedItems": [
    {
      "profileImage": "https://i.pravatar.cc/150?img=1",
      "username": "erluxman",
      "timeAgo": "2 mins ago",
      "rank": "Top 5% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Read a news article📰",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 6,
      "comments": 8,
      "shares": 2,
      "commenters": ["Bijay", "Prakash", "5 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=2",
      "username": "Donn Felker",
      "timeAgo": "5 mins ago",
      "rank": "Top 10% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Wake up before 5 AM 🌅 daily",
      "progress": 85,
      "timeSpent": "2.5 hours",
      "streak": 30,
      "reactions": 12,
      "comments": 15,
      "shares": 4,
      "commenters": ["Kaushik", "Kapil", "3 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=3",
      "username": "Kaushik Gopal",
      "timeAgo": "10 mins ago",
      "rank": "Top 15% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "100 days of coding streak! 💻",
      "progress": 100,
      "points": 500,
      "streak": 100,
      "reactions": 25,
      "comments": 20,
      "shares": 8,
      "commenters": ["Nabin", "Prakash", "7 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=4",
      "username": "Kapil Amagain",
      "timeAgo": "15 mins ago",
      "rank": "Top 20% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "Just hit my 100-day streak of daily exercise! 💪\n\nKey tips that helped:\n• Morning routine\n• Accountability partner\n• Progress tracking\n\nWhat's your longest streak?",
      "reactions": 128,
      "comments": 32,
      "shares": 12,
      "commenters": ["Donn", "Kaushik", "5 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=5",
      "username": "Nabin Paudel",
      "timeAgo": "20 mins ago",
      "rank": "Top 25% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Write technical blog post ✍️",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "Medium",
      "reactions": 8,
      "comments": 12,
      "shares": 3,
      "commenters": ["Kapil", "Donn", "4 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=6",
      "username": "erluxman",
      "timeAgo": "25 mins ago",
      "rank": "Top 30% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "30 minutes of meditation 🧘‍♂️ daily",
      "progress": 60,
      "timeSpent": "1.5 hours",
      "streak": 15,
      "reactions": 15,
      "comments": 18,
      "shares": 5,
      "commenters": ["Kaushik", "Nabin", "6 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=7",
      "username": "Donn Felker",
      "timeAgo": "30 mins ago",
      "rank": "Top 35% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "50 books read this year! 📚",
      "progress": 100,
      "points": 1000,
      "streak": 50,
      "reactions": 45,
      "comments": 30,
      "shares": 15,
      "commenters": ["Kapil", "Prakash", "8 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=8",
      "username": "Kaushik Gopal",
      "timeAgo": "35 mins ago",
      "rank": "Top 40% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The Pomodoro Technique has been a game-changer! 🍅\n\nHere's how I use it:\n• 25 minutes focus\n• 5 minutes break\n• 4 sessions = long break\n\nWhat's your favorite productivity technique?",
      "reactions": 156,
      "comments": 45,
      "shares": 18,
      "commenters": ["Donn", "Nabin", "7 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=9",
      "username": "Kapil Amagain",
      "timeAgo": "40 mins ago",
      "rank": "Top 45% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Review pull requests 🔍",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 10,
      "comments": 15,
      "shares": 2,
      "commenters": ["Kaushik", "Prakash", "3 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=10",
      "username": "Nabin Paudel",
      "timeAgo": "45 mins ago",
      "rank": "Top 50% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily code review 📝",
      "progress": 75,
      "timeSpent": "1 hour",
      "streak": 20,
      "reactions": 18,
      "comments": 22,
      "shares": 6,
      "commenters": ["Donn", "Kapil", "5 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=11",
      "username": "erluxman",
      "timeAgo": "50 mins ago",
      "rank": "Top 55% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "200 contributions on GitHub! 🚀",
      "progress": 100,
      "points": 2000,
      "streak": 200,
      "reactions": 89,
      "comments": 35,
      "shares": 25,
      "commenters": ["Kaushik", "Nabin", "9 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=12",
      "username": "Donn Felker",
      "timeAgo": "55 mins ago",
      "rank": "Top 60% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "Time blocking has transformed my productivity! ⏰\n\nMy schedule:\n• Morning: Deep work\n• Afternoon: Meetings\n• Evening: Learning\n\nHow do you structure your day?",
      "reactions": 234,
      "comments": 67,
      "shares": 34,
      "commenters": ["Kapil", "Prakash", "12 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=13",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 65% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Update documentation 📚",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "Medium",
      "reactions": 12,
      "comments": 18,
      "shares": 4,
      "commenters": ["Donn", "Nabin", "4 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=14",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 70% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily pair programming 👥",
      "progress": 90,
      "timeSpent": "3 hours",
      "streak": 25,
      "reactions": 28,
      "comments": 32,
      "shares": 8,
      "commenters": ["Kaushik", "Prakash", "7 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=15",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 75% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "1000 followers on Twitter! 🐦",
      "progress": 100,
      "points": 1000,
      "streak": 30,
      "reactions": 156,
      "comments": 45,
      "shares": 89,
      "commenters": ["Donn", "Kapil", "15 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=16",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 80% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The power of saying 'No'! 🚫\n\nKey learnings:\n• Focus on priorities\n• Set boundaries\n• Quality over quantity\n\nHow do you handle requests?",
      "reactions": 345,
      "comments": 89,
      "shares": 45,
      "commenters": ["Kaushik", "Nabin", "18 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=17",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 85% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Fix critical bug 🐛",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 15,
      "comments": 25,
      "shares": 5,
      "commenters": ["Kapil", "Prakash", "6 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=18",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 90% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily code kata 💪",
      "progress": 95,
      "timeSpent": "2 hours",
      "streak": 40,
      "reactions": 32,
      "comments": 38,
      "shares": 12,
      "commenters": ["Donn", "Nabin", "8 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=19",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 95% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "First tech conference talk! 🎤",
      "progress": 100,
      "points": 2000,
      "streak": 1,
      "reactions": 234,
      "comments": 78,
      "shares": 156,
      "commenters": ["Kaushik", "Prakash", "25 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=20",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 100% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The importance of taking breaks! ☕\n\nMy routine:\n• Every 2 hours\n• 10-minute walk\n• Deep breathing\n\nWhat's your break routine?",
      "reactions": 456,
      "comments": 123,
      "shares": 67,
      "commenters": ["Donn", "Kapil", "30 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=21",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 105% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Deploy to production 🚀",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 20,
      "comments": 30,
      "shares": 8,
      "commenters": ["Donn", "Kaushik", "7 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=22",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 110% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily standup meeting 📊",
      "progress": 80,
      "timeSpent": "1 hour",
      "streak": 35,
      "reactions": 15,
      "comments": 20,
      "shares": 5,
      "commenters": ["Kapil", "Nabin", "4 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=23",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 115% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "First open source contribution! 🌟",
      "progress": 100,
      "points": 500,
      "streak": 1,
      "reactions": 89,
      "comments": 34,
      "shares": 45,
      "commenters": ["Donn", "Prakash", "12 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=24",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 120% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The power of morning journaling! 📝\n\nBenefits:\n• Clear mind\n• Better focus\n• Goal setting\n\nDo you journal?",
      "reactions": 234,
      "comments": 67,
      "shares": 89,
      "commenters": ["Kaushik", "Nabin", "15 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=25",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 125% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Code review feedback 📋",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "Medium",
      "reactions": 12,
      "comments": 18,
      "shares": 3,
      "commenters": ["Donn", "Kapil", "4 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=26",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 130% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily code review 📝",
      "progress": 85,
      "timeSpent": "2 hours",
      "streak": 45,
      "reactions": 25,
      "comments": 30,
      "shares": 8,
      "commenters": ["Kaushik", "Prakash", "6 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=27",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 135% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "1000 commits this year! 💻",
      "progress": 100,
      "points": 1000,
      "streak": 1000,
      "reactions": 156,
      "comments": 45,
      "shares": 67,
      "commenters": ["Kapil", "Nabin", "18 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=28",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 140% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The importance of deep work! 🧠\n\nMy approach:\n• No distractions\n• Focused blocks\n• Regular breaks\n\nHow do you maintain focus?",
      "reactions": 345,
      "comments": 89,
      "shares": 123,
      "commenters": ["Donn", "Prakash", "25 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=29",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 145% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Update dependencies 🔄",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 15,
      "comments": 20,
      "shares": 5,
      "commenters": ["Kaushik", "Nabin", "5 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=30",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 150% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily team sync 🤝",
      "progress": 90,
      "timeSpent": "1.5 hours",
      "streak": 30,
      "reactions": 18,
      "comments": 25,
      "shares": 6,
      "commenters": ["Donn", "Kapil", "7 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=31",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 155% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "First tech book published! 📚",
      "progress": 100,
      "points": 5000,
      "streak": 1,
      "reactions": 456,
      "comments": 123,
      "shares": 234,
      "commenters": ["Kaushik", "Prakash", "35 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=32",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 160% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The power of automation! ⚡\n\nMy setup:\n• CI/CD pipelines\n• Automated testing\n• Deployment scripts\n\nWhat do you automate?",
      "reactions": 567,
      "comments": 156,
      "shares": 89,
      "commenters": ["Kapil", "Nabin", "28 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=33",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 165% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Performance optimization 🚀",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 25,
      "comments": 35,
      "shares": 8,
      "commenters": ["Donn", "Prakash", "9 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=34",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 170% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily code review 📝",
      "progress": 95,
      "timeSpent": "2.5 hours",
      "streak": 50,
      "reactions": 32,
      "comments": 40,
      "shares": 12,
      "commenters": ["Kaushik", "Nabin", "10 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=35",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 175% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "1000 followers on LinkedIn! 👥",
      "progress": 100,
      "points": 1000,
      "streak": 30,
      "reactions": 234,
      "comments": 67,
      "shares": 156,
      "commenters": ["Donn", "Kapil", "20 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=36",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 180% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The importance of code reviews! 👀\n\nBenefits:\n• Better code quality\n• Knowledge sharing\n• Team collaboration\n\nHow do you review code?",
      "reactions": 456,
      "comments": 123,
      "shares": 89,
      "commenters": ["Kaushik", "Prakash", "30 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=37",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 185% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Update API documentation 📚",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "Medium",
      "reactions": 18,
      "comments": 25,
      "shares": 6,
      "commenters": ["Kapil", "Nabin", "5 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=38",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 190% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily team standup 📊",
      "progress": 85,
      "timeSpent": "1 hour",
      "streak": 40,
      "reactions": 15,
      "comments": 20,
      "shares": 4,
      "commenters": ["Donn", "Prakash", "6 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=39",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 195% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "First tech podcast episode! 🎙️",
      "progress": 100,
      "points": 2000,
      "streak": 1,
      "reactions": 345,
      "comments": 89,
      "shares": 234,
      "commenters": ["Kaushik", "Nabin", "25 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=40",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 200% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The power of pair programming! 👥\n\nBenefits:\n• Better code quality\n• Knowledge sharing\n• Faster learning\n\nDo you pair program?",
      "reactions": 567,
      "comments": 156,
      "shares": 89,
      "commenters": ["Donn", "Kapil", "35 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=41",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 205% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Fix security vulnerability 🔒",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 25,
      "comments": 35,
      "shares": 8,
      "commenters": ["Kaushik", "Prakash", "9 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=42",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 210% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily code review 📝",
      "progress": 90,
      "timeSpent": "2 hours",
      "streak": 55,
      "reactions": 28,
      "comments": 35,
      "shares": 10,
      "commenters": ["Kapil", "Nabin", "8 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=43",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 215% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "First tech conference talk! 🎤",
      "progress": 100,
      "points": 3000,
      "streak": 1,
      "reactions": 456,
      "comments": 123,
      "shares": 345,
      "commenters": ["Donn", "Prakash", "40 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=44",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 220% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The importance of code quality! ✨\n\nMy approach:\n• Clean code\n• Testing\n• Documentation\n\nHow do you maintain quality?",
      "reactions": 678,
      "comments": 189,
      "shares": 123,
      "commenters": ["Kaushik", "Nabin", "45 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=45",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 225% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Update dependencies 🔄",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "Medium",
      "reactions": 15,
      "comments": 20,
      "shares": 5,
      "commenters": ["Donn", "Kapil", "4 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=46",
      "username": "erluxman",
      "timeAgo": "1 hour ago",
      "rank": "Top 230% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily team sync 🤝",
      "progress": 85,
      "timeSpent": "1.5 hours",
      "streak": 60,
      "reactions": 20,
      "comments": 25,
      "shares": 6,
      "commenters": ["Kaushik", "Prakash", "7 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=47",
      "username": "Donn Felker",
      "timeAgo": "1 hour ago",
      "rank": "Top 235% this week",
      "activityType": "milestone",
      "title": "Reached a Milestone",
      "subtitle": "First tech book published! 📚",
      "progress": 100,
      "points": 5000,
      "streak": 1,
      "reactions": 567,
      "comments": 156,
      "shares": 345,
      "commenters": ["Kapil", "Nabin", "50 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=48",
      "username": "Kaushik Gopal",
      "timeAgo": "1 hour ago",
      "rank": "Top 240% this week",
      "activityType": "feed",
      "title": "Productivity Tip",
      "subtitle":
          "The power of automation! ⚡\n\nMy setup:\n• CI/CD pipelines\n• Automated testing\n• Deployment scripts\n\nWhat do you automate?",
      "reactions": 789,
      "comments": 234,
      "shares": 156,
      "commenters": ["Donn", "Prakash", "60 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=49",
      "username": "Kapil Amagain",
      "timeAgo": "1 hour ago",
      "rank": "Top 245% this week",
      "activityType": "todo",
      "title": "Completed a todo",
      "subtitle": "Performance optimization 🚀",
      "progress": 100,
      "timeRemaining": "Completed",
      "priority": "High",
      "reactions": 30,
      "comments": 40,
      "shares": 10,
      "commenters": ["Kaushik", "Nabin", "12 others"]
    },
    {
      "profileImage": "https://i.pravatar.cc/150?img=50",
      "username": "Nabin Paudel",
      "timeAgo": "1 hour ago",
      "rank": "Top 250% this week",
      "activityType": "habit",
      "title": "Started a Habit",
      "subtitle": "Daily code review 📝",
      "progress": 95,
      "timeSpent": "2.5 hours",
      "streak": 70,
      "reactions": 35,
      "comments": 45,
      "shares": 15,
      "commenters": ["Donn", "Kapil", "15 others"]
    }
  ]
};
