// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-NDUweGDgeU7gbqFRm_hzjuN3n1QQ0I',
    appId: '1:949878462839:web:07f6aa2e43d3d03b8fa972',
    messagingSenderId: '949878462839',
    projectId: 'productive-78c0e',
    authDomain: 'productive-78c0e.firebaseapp.com',
    storageBucket: 'productive-78c0e.firebasestorage.app',
    measurementId: 'G-KZC3EX3J71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEO6eWnJjXKzvcr21T9TWd95DVeAgIXUI',
    appId: '1:949878462839:android:66b5b9ed9f3f25a88fa972',
    messagingSenderId: '949878462839',
    projectId: 'productive-78c0e',
    storageBucket: 'productive-78c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrthrXBJH8WOuSPvzCBu3032AvpMywTA',
    appId: '1:949878462839:ios:1bb3568515d1bf9d8fa972',
    messagingSenderId: '949878462839',
    projectId: 'productive-78c0e',
    storageBucket: 'productive-78c0e.firebasestorage.app',
    androidClientId: '949878462839-fig10pf8rsn101dhamq1le1m703t8brr.apps.googleusercontent.com',
    iosClientId: '949878462839-sd3rk5pkmsq2osmh47afaid5ltcstujh.apps.googleusercontent.com',
    iosBundleId: 'com.erluxman.productive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUrthrXBJH8WOuSPvzCBu3032AvpMywTA',
    appId: '1:949878462839:ios:1bb3568515d1bf9d8fa972',
    messagingSenderId: '949878462839',
    projectId: 'productive-78c0e',
    storageBucket: 'productive-78c0e.firebasestorage.app',
    androidClientId: '949878462839-fig10pf8rsn101dhamq1le1m703t8brr.apps.googleusercontent.com',
    iosClientId: '949878462839-sd3rk5pkmsq2osmh47afaid5ltcstujh.apps.googleusercontent.com',
    iosBundleId: 'com.erluxman.productive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi-NDUweGDgeU7gbqFRm_hzjuN3n1QQ0I',
    appId: '1:949878462839:web:7b48473b05c9dfa18fa972',
    messagingSenderId: '949878462839',
    projectId: 'productive-78c0e',
    authDomain: 'productive-78c0e.firebaseapp.com',
    storageBucket: 'productive-78c0e.firebasestorage.app',
    measurementId: 'G-PNN5V2BDGT',
  );

}