
### Variables
@baseUrl = http://localhost:5002/productive-78c0e/us-central1/api
@todoId = TODO_ID

### Create a new todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "Test task",
  "description": "make a testing api"
}
### Create a new todo on backend
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "Test task",
  "description": "make a testing api",
  "completed": false,
  "createdAt": "2023-10-01T12:00:00Z",
  "category":"general"
}

### Stripe Proxy
POST {{baseUrl}}/stripeProxy
Content-Type: application/json

{
  "title": "Test task",
  "description": "make a testing api",
  "completed": false,
  "createdAt": "2023-10-01T12:00:00Z",
  "category":"general"
}

### Get all todos
GET {{baseUrl}}/todos

### Update a todo
PUT {{baseUrl}}/todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated todo title",
  "description": "Updated description",
  "completed": true
}

### Delete a todo
DELETE {{baseUrl}}/todos/{{todoId}} 